version: 2.0
jobs:
  build:
    docker:
    - image: typelead/eta:0.8.6b4
    env:
    - ETA_JAVA_ARGS: -Xms1024M -Xmx1024M
    steps:
    - checkout
    - run:
        name: Init Benchmarks
        command: ./scripts/init.sh
    - run:
        name: Run Fast Benchmarks
        command: ./scripts/fast-benchmarks.sh
    - run:
        name: Run Slow Benchmarks
        command: ./scripts/slow-benchmarks.sh
        no_output_timeout: 3h

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
