version: 2.0
jobs:
  build:
    docker:
    - image: typelead/eta:latest
    environment:
      ETA_JAVA_ARGS: -Xss512M -Xms1024M -Xmx1024M
    steps:
    - checkout
    - run:
        name: Init Bnechmarks
        command: ./scripts/init.sh
    - run:
        name: Fast Benchmarks
        command: ./scripts/fast-benchmarks.sh
        no_output_timeout: 1h
    - run:
        name: Slow Benchmarks
        command: ./scripts/slow-benchmarks.sh
        no_output_timeout: 2h

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
